<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="IN3261049W1" failures="1" tests="7" name="LoginTest" time="56.141" errors="0" timestamp="2022-08-11T08:43:37 IST">
  <testcase classname="com.learnautomation.testcases.LoginToApplication" name="Login" time="0.035">
    <skipped/>
  </testcase> <!-- Login -->
  <testcase classname="com.learnautomation.testcases.LoginToApplication" name="Login" time="10.609"/>
  <testcase classname="com.learnautomation.testcases.LoginToApplication" name="Login" time="5.549"/>
  <testcase classname="com.learnautomation.testcases.LoginToApplication" name="Login" time="5.003"/>
  <testcase classname="com.learnautomation.testcases.LoginToApplication" name="Login" time="4.736"/>
  <testcase classname="com.learnautomation.testcases.LoginToApplication" name="Login" time="5.232"/>
  <testcase classname="com.learnautomation.testcases.LoginToApplication" name="Login" time="2.774">
    <failure type="java.lang.AssertionError" message="Login Failed expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Login Failed expected [true] but found [false]
at com.learnautomation.testcases.LoginToApplication.Login(LoginToApplication.java:31)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- Login -->
</testsuite> <!-- LoginTest -->
